[package]
name = "abort"
version = "0.1.2"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Abnormal termination (stable, no_std)"
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
nightly = []
